name: openlist_native_ui
description: "A new Flutter openlist native ui project."
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jaguar_flutter_asset: ^3.0.0
  shared_preferences: ^2.1.1
  #  gtads: ^1.5.0
  #  #字节穿山甲广告
  #  gtads_csj: ^1.5.0
  #  #腾讯优量汇广告
  #  gtads_ylh: ^1.5.0
  intl: '>=0.19.0 <= 1.0.0'
#  openlist_background_service:
#    path: ../openlist_background_service
#  openlist_global:
#    path: ../openlist_global
  openlist_background_service: ^0.0.1
  openlist_global: ^0.0.1
  #  flutter_inappwebview: ^6.1.5
  get: ^4.7.2
  url_launcher: ^6.1.11
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  dio: ^5.8.0+1
  tdesign_flutter: ^0.2.0
  package_info_plus: ^8.3.0
  provider: ^6.0.2
  cached_network_image: ^3.4.1
  flutter_breadcrumb: ^1.0.1
  video_player: ^2.10.0
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  #  flutter_distributor: ^0.4.5
  intl_utils: ^2.8.3
  build_runner:
  flutter_gen_runner:

flutter_gen:
  assets:
    - lib/l10n/*.arb

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/images/splash/
    - assets/files/
